name: Run Piper-TTS App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Ensure compatibility with Node.js 20

    - name: Set up Python 3.10.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12  # Use the required version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y calibre ffmpeg espeak-ng
        pip install -r requirements.txt
        python -m nltk.downloader punkt

    - name: Run Piper-TTS Gradio Interface
      run: |
        python gradio_gui.py &
        sleep 10  # Allow the server time to start
        curl -I http://localhost:7860 || exit 1
